# Generated by Django 5.1.4 on 2024-12-12 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_alter_like_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='timestamp',
        ),
    ]
