# Generated by Django 5.1.4 on 2024-12-18 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0005_remove_like_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advantage',
            name='likes',
        ),
        migrations.AddField(
            model_name='advantage',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='like',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='achievements.advantage'),
        ),
    ]
