# Generated by Django 5.1.4 on 2024-12-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0008_delete_advantage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='favorite',
        ),
        migrations.AddField(
            model_name='achievement',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
