# Generated by Django 5.1.4 on 2024-12-19 19:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0009_remove_achievement_favorite_achievement_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('achievement', 'user')},
        ),
    ]
