# Generated by Django 5.1.4 on 2024-12-19 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0010_alter_like_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='likes',
            new_name='like_count',
        ),
        migrations.AlterField(
            model_name='like',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='achievements.achievement'),
        ),
    ]
